### ISSUE TITLE
Use of defu in CookieInformation provider in wrong order

### ISSUE THREAD

**Issue by henriksjodahl** [weareheavy/nuxt-cookie-consent#1]
The default value is in the wrong order. culture: 'EN' always override the configured value.

https://github.com/weareheavy/nuxt-cookie-consent/blob/58c03ca7e5c07c51411e188a8836cb2ae7554208/src/module.ts#L52-L57

should be
```
config = defu( 
   config, 
   { 
     culture: 'EN', 
   }, 
 ) 
```

https://github.com/unjs/defu?tab=readme-ov-file#usage

**Comment by tkjaergaard** [comment]
@henriksjodahl  Good catch! I'll look into it 🙂

**Comment by tkjaergaard** [comment]
@henriksjodahl Try pulling version 1.0.3 and see if that helps 🙂

**Comment by henriksjodahl** [comment]
Perfect, thanks!
