### ISSUE TITLE
Not reacting to state changes?

### ISSUE THREAD

**Issue by shintaii** [weareheavy/nuxt-cookie-consent#9]
I use the cookbiebot service. I have the following in the default.vue (layout) in nuxt. 

But changes are not triggered. The cookiebot banner shows, it works (i can see the cookies from cookiebot), but the plugin does not reacte to the state changes. I'm also using the Nuxt Gtag Module. 

```
const { state } = useCookieConsent()
// when the state changes, we want to update the gtag consent
watch(() => state, () => {
    console.log('state changed', state.value)
    if (state.value.statistic && state.value.marketing && state.value.necessary, state.value.functional, state.value.unclassified) {
        allConsentGranted()
    }

    if (state.value.statistic) {
        consentAnalytics()
    }

    if (state.value.marketing) {
        consentMarketing()
    }

    if (state.value.necessary) {
        consentNecessary()
    }
})

function allConsentGranted() {
  const { gtag } = useGtag()
  gtag('consent', 'update', {
    ad_user_data: 'granted',
    ad_personalization: 'granted',
    ad_storage: 'granted',
    analytics_storage: 'granted',
    functionality_storage: 'granted',
    security_storage: 'granted',
    personalization_storage: 'granted',
  })
}

function consentAnalytics() {
  console.log('consentAnalytics')
  const { gtag } = useGtag()
  gtag('consent', 'update', {
    analytics_storage: 'granted',
    })
}

function consentMarketing() {
  console.log('consentMarketing')
  const { gtag } = useGtag()
  gtag('consent', 'update', {
    ad_user_data: 'granted',
    ad_personalization: 'granted',
    ad_storage: 'granted',
  })
}

function consentNecessary() {
  console.log('consentNecessary')
  const { gtag } = useGtag()
  gtag('consent', 'update', {
    functionality_storage: 'granted',
    security_storage: 'granted',
    personalization_storage: 'granted',
  })
}
```

**Comment by tkjaergaard** [comment]
@shintaii

The change in the state for cookiebot is tracked using the "CookiebotOnAccept" event fired on window.

It the checks for the `window.Cookiebot.consent` variable to be set.

https://github.com/weareheavy/nuxt-cookie-consent/blob/main/src/runtime/plugins/cookiebot.plugin.ts#L79-L93

https://www.cookiebot.com/en/developer/#h-event-handling

Can you verify if this event is being called? Maybe add something like this to through the devtools console before accepting the cookies:


```js
window.addEventListener('CookiebotOnAccept', (e) => {
  console.log('[CONSENT]', window?.Cookiebot?.consent)
})
```

**Comment by shintaii** [comment]
Thanks! 

That worked out, i added the event and eveything worked out, and now i can control the premissions.

**Comment by tkjaergaard** [comment]
But the module should pick up on these events in [cookibot.plugin.ts](https://github.com/weareheavy/nuxt-cookie-consent/blob/main/src/runtime/plugins/cookiebot.plugin.ts#L79-L93), and update the `state` accordingly.

Can you make a minimal reproduction?

**Comment by tkjaergaard** [comment]
Just out of curiosity, since state is a Ref what happens if you change your watch to: `watch(state, () => {`?

**Comment by tkjaergaard** [comment]
@shintaii i can reproduce the watch not working in a clean Nuxt Project. But it seems that `watchEffect` works:

https://stackblitz.com/edit/nuxt-starter-39uh5t?file=app.vue

I would recommend you to drop your listener on window and instead use `watchEffect` on the state. But ofc, totally up to you 🙂

**Comment by tkjaergaard** [comment]
@shintaii 

https://github.com/nuxt/nuxt/issues/29291#issuecomment-2395550952

**Comment by felix-schett** [comment]
I currently have a similar/realted Issue to this one where the state is not updated.
I am using Cookiebot and the following component:

```
<script setup lang="ts">
  const { state: consent } = useCookieConsent()
</script>

<template>
  <div
    v-if="consent.statistic"
    class="bg-green-200 p-4 rounded-lg mb-4"
  >
    <p>This is only visible if the "statistic" category has been approved.</p>
  </div>
  <div
    v-if="consent.marketing"
    class="bg-blue-200 p-4 rounded-lg"  
  >
    <p>This is only visible if the "marketing" category has been approved.</p>
  </div>
  <button
    class="bg-green text-black px-4 py-2 rounded-lg mr-4"
    @click="cookieConsentShow()"
  >
    Change Cookie Settinga
  </button>
</template>
```

Issue:
The state is not updated when previously accepted consents are denied.

Reproduction:
1. 'Allow selection' or 'Allow all'
2. Show banner again
3. 'Deny'

Expected behaviour:
State is updated - all consents are set to false

Actual behaviour:
State does not change.


I had a quick a look at the soruce code and the cookiebot docs.
In my opinion the state should also lsiten for the `CookiebotCallback_OnDecline` and not only `CookiebotCallback_OnAccept`.
